; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Apr 07 2021 11:58:58 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAACX9F5XTGU4:
	dc.w DATAACX9F5XTGU4_0-DATAACX9F5XTGU4, DATAACX9F5XTGU4_1-DATAACX9F5XTGU4
	dc.w DATAACX9F5XTGU4_2-DATAACX9F5XTGU4
DATAACX9F5XTGU4_0: dc.b $4
	dc.b $ED, $7, $0, $0, $F0
	dc.b $ED, $7, $8, $0, $0
	dc.b $D, $4, $0, $8, $F0
	dc.b $D, $4, $8, $8, $0
DATAACX9F5XTGU4_1: dc.b $3
	dc.b $EC, $7, $0, $0, $EE
	dc.b $EC, $7, $8, $0, $FE
	dc.b $C, $C, $0, $A, $EE
DATAACX9F5XTGU4_2: dc.b $4
	dc.b $ED, $7, $0, $E, $F0
	dc.b $ED, $7, $8, $E, $0
	dc.b $D, $4, $0, $16, $F0
	dc.b $D, $4, $8, $16, $0
	even